// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMdsKM6nKcCyP0NB2UA3DG0XyU3LMnUH8',
    appId: '1:837904843520:web:9622943e004ae44be669e5',
    messagingSenderId: '837904843520',
    projectId: 'prato-8b294',
    authDomain: 'prato-8b294.firebaseapp.com',
    storageBucket: 'prato-8b294.appspot.com',
    measurementId: 'G-6MDE1D770H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdRN1Sa5ilYnJvXBGkA83aR0vYnxNqJk',
    appId: '1:837904843520:android:634cae62f03bc27ae669e5',
    messagingSenderId: '837904843520',
    projectId: 'prato-8b294',
    storageBucket: 'prato-8b294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDygzJt1gJVF5Y7hwd1EC1QD983v1y2dmE',
    appId: '1:837904843520:ios:cc6ff344f2379358e669e5',
    messagingSenderId: '837904843520',
    projectId: 'prato-8b294',
    storageBucket: 'prato-8b294.appspot.com',
    iosClientId: '837904843520-um3g17aak2jjl7o4qlrig386r3gophjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.prato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDygzJt1gJVF5Y7hwd1EC1QD983v1y2dmE',
    appId: '1:837904843520:ios:cc6ff344f2379358e669e5',
    messagingSenderId: '837904843520',
    projectId: 'prato-8b294',
    storageBucket: 'prato-8b294.appspot.com',
    iosClientId: '837904843520-um3g17aak2jjl7o4qlrig386r3gophjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.prato',
  );
}
